# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/royce/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="avit"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias vi="vim"
alias g='git'
alias l='log'
alias gs='git status'
alias gsh='git show'
alias ga='git add'
alias gm='git merge'
alias gb='git branch'
alias gd='git diff'
alias gc='git commit'
alias gco='git checkout'
alias gpl='git pull'
alias gps='git push'
alias glg='git log --stat'
alias glgg='git log --graph'
alias grm='git rm'
alias grs='git reset'
alias grv='git rev-list --count'
alias grb='git rebase'
alias gcr='git cherry'
alias cppr='cap production'
alias grp='grep -rl'
alias ..=' cd ..; ls'
alias ...=' cd ..; cd ..; ls'
alias ....=' cd ..; cd ..; cd ..; ls'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias cd..='..'
alias cd...='...'
alias cd....='....'
alias bi='bundle install'
alias rdd='rake db:drop; rake db:migrate; rake db:seed'
alias sshtest='ssh nam@test.starfandom.com'
alias gsl='git stash list'

export ic=/Users/royce/Library/Mobile\ Documents/com\~apple\~CloudDocs/
export dev=/Users/royce/Library/Mobile\ Documents/com\~apple\~CloudDocs/develop/
export melo=/Users/royce/Library/Mobile\ Documents/com\~apple\~CloudDocs/develop/Hyperconnect/dating-web
export li5=/Users/royce/Library/Mobile\ Documents/com\~apple\~CloudDocs/likelion/likelion5th
export snulion=/Users/royce/Library/Mobile\ Documents/com\~apple\~CloudDocs/likelion/likelion5th/SNULionMain
export sk=/Users/royce/Library/Mobile\ Documents/com\~apple\~CloudDocs/MOOC/sung\ kim/projects/

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
# export SECRET_KEY="dn&k2krgu&tc%gj2yk(d3lv8gh1)x$5qzx26#e@^51k@7^fsvf"
# export DJANGO_SETTINGS_MODULE="dating.settings.local"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
